/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package strategypattern.Presentation;

import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.JTextField;
import strategypattern.Abstraction.Clock;
import strategypattern.Abstraction.SoundControl;
import strategypattern.Abstraction.SoundOffCommand;
import strategypattern.Abstraction.SoundOnCommand;
import strategypattern.Control.ClockControl;

/**
 *
 * @author rebirth
 */
public class ClockPresentation extends javax.swing.JFrame {
    SoundControl soundControl = new SoundControl();
    ClockControl clockControl;

    /**
     * Creates new form NewJFrame
     */
    public ClockPresentation() {
        this.clockControl = new ClockControl(this);
        initComponents();
    }

    public void draw(JPanel panelAnalogue, JPanel panelDigital) {
        clockPanel.removeAll();
        clockPanel1.removeAll();

        clockPanel.add(panelAnalogue);
        clockPanel1.add(panelDigital);

        panelAnalogue.setVisible(false);
        panelAnalogue.setVisible(true);
        panelAnalogue.repaint();

        panelDigital.setVisible(false);
        panelDigital.setVisible(true);
        panelDigital.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displaySettingsGroup = new javax.swing.ButtonGroup();
        soundSettingsGroup = new javax.swing.ButtonGroup();
        clockPanel = new javax.swing.JPanel();
        displaySettings = new javax.swing.JPanel();
        setUTC = new javax.swing.JRadioButton();
        setMET = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        setEST = new javax.swing.JRadioButton();
        SoundSettings = new javax.swing.JPanel();
        noSoundButton = new javax.swing.JRadioButton();
        tickSoundButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        clockPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clockPanel.setBackground(new java.awt.Color(204, 204, 204));
        clockPanel.setLayout(new java.awt.GridLayout(1, 0));

        displaySettings.setBackground(new java.awt.Color(204, 204, 204));

        displaySettingsGroup.add(setUTC);
        setUTC.setSelected(true);
        setUTC.setText("UTC");
        setUTC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setUTCMouseClicked(evt);
            }
        });
        setUTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setUTCActionPerformed(evt);
            }
        });

        displaySettingsGroup.add(setMET);
        setMET.setText("MET");
        setMET.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setMETMouseClicked(evt);
            }
        });
        setMET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMETActionPerformed(evt);
            }
        });

        jLabel1.setText("Timezone");

        displaySettingsGroup.add(setEST);
        setEST.setText("EST");
        setEST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setESTMouseClicked(evt);
            }
        });
        setEST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setESTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout displaySettingsLayout = new javax.swing.GroupLayout(displaySettings);
        displaySettings.setLayout(displaySettingsLayout);
        displaySettingsLayout.setHorizontalGroup(
            displaySettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displaySettingsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(displaySettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(setEST)
                    .addComponent(jLabel1)
                    .addComponent(setMET)
                    .addComponent(setUTC))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        displaySettingsLayout.setVerticalGroup(
            displaySettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displaySettingsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setUTC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setMET)
                .addGap(3, 3, 3)
                .addComponent(setEST)
                .addGap(12, 12, 12))
        );

        SoundSettings.setBackground(new java.awt.Color(204, 204, 204));

        soundSettingsGroup.add(noSoundButton);
        noSoundButton.setSelected(true);
        noSoundButton.setText("None");
        noSoundButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noSoundButtonMouseClicked(evt);
            }
        });

        soundSettingsGroup.add(tickSoundButton);
        tickSoundButton.setText("Tick");
        tickSoundButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tickSoundButtonMouseClicked(evt);
            }
        });

        jLabel2.setText("Sound");

        javax.swing.GroupLayout SoundSettingsLayout = new javax.swing.GroupLayout(SoundSettings);
        SoundSettings.setLayout(SoundSettingsLayout);
        SoundSettingsLayout.setHorizontalGroup(
            SoundSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SoundSettingsLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(SoundSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tickSoundButton)
                    .addComponent(noSoundButton))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        SoundSettingsLayout.setVerticalGroup(
            SoundSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SoundSettingsLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noSoundButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tickSoundButton)
                .addGap(39, 39, 39))
        );

        clockPanel1.setBackground(new java.awt.Color(204, 204, 204));
        clockPanel1.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clockPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displaySettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clockPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SoundSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clockPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clockPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(displaySettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SoundSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setUTCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setUTCMouseClicked
        //
    }//GEN-LAST:event_setUTCMouseClicked

    private void setMETMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setMETMouseClicked
        //
    }//GEN-LAST:event_setMETMouseClicked

    private void noSoundButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noSoundButtonMouseClicked
        SoundOffCommand soundOff = new SoundOffCommand(clockControl);
        soundControl.setCommand(soundOff);
        soundControl.buttonWasPressed();
    }//GEN-LAST:event_noSoundButtonMouseClicked

    private void tickSoundButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tickSoundButtonMouseClicked
        SoundOnCommand soundOn = new SoundOnCommand(clockControl);
        soundControl.setCommand(soundOn);
        soundControl.buttonWasPressed();
    }//GEN-LAST:event_tickSoundButtonMouseClicked

    private void setUTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setUTCActionPerformed
        clockControl.setUTC();
    }//GEN-LAST:event_setUTCActionPerformed

    private void setESTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setESTMouseClicked

    }//GEN-LAST:event_setESTMouseClicked

    private void setMETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMETActionPerformed
        clockControl.setMET();
    }//GEN-LAST:event_setMETActionPerformed

    private void setESTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setESTActionPerformed
        clockControl.setEST();
    }//GEN-LAST:event_setESTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SoundSettings;
    private javax.swing.JPanel clockPanel;
    private javax.swing.JPanel clockPanel1;
    private javax.swing.JPanel displaySettings;
    private javax.swing.ButtonGroup displaySettingsGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton noSoundButton;
    private javax.swing.JRadioButton setEST;
    private javax.swing.JRadioButton setMET;
    private javax.swing.JRadioButton setUTC;
    private javax.swing.ButtonGroup soundSettingsGroup;
    private javax.swing.JRadioButton tickSoundButton;
    // End of variables declaration//GEN-END:variables
}
