/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package strategypattern.Presentation;

/**
 *
 * @author rebirth
 */
public class DigitalClockPresentation extends javax.swing.JPanel {

    /**
     * Creates new form digitalClockPresentation
     */
    public DigitalClockPresentation() {
        initComponents();
        setText("00:00:00");
    }
    
    public void setText(String str) {
        this.digitalClock.setText(str);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        digitalClock = new javax.swing.JLabel();

        digitalClock.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        digitalClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        digitalClock.setText("00:00:00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(digitalClock, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(digitalClock, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel digitalClock;
    // End of variables declaration//GEN-END:variables
}
